# Generated by Django 4.2.20 on 2025-05-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrativelevels", "0002_alter_administrativelevel_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="administrativelevel",
            name="order",
            field=models.PositiveIntegerField(
                help_text="Defines the level in hierarchy (e.g., 1 for Country, 2 for Region)",
                unique=True,
            ),
        ),
    ]
