# Generated by Django 4.2.20 on 2025-05-02 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("administrativelevels", "0003_alter_administrativelevel_order"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="administrativeunit",
            unique_together={("name", "level", "parent")},
        ),
    ]
