# Generated by Django 4.2.20 on 2025-11-07 14:57

from django.db import migrations, models


def get_hierarchy_name(administrative_unit):
    if administrative_unit.parent is None:
        return "{} {}".format(administrative_unit.level.name, administrative_unit.name)
    return "{} {}, {}".format(administrative_unit.level.name, administrative_unit.name,
                              get_hierarchy_name(administrative_unit.parent))


def populate_hierarchy_name(apps, schema_editor):
    AdministrativeUnit = apps.get_model('administrativelevels', 'AdministrativeUnit')
    qs = AdministrativeUnit.objects.all()
    for obj in qs:
        obj.hierarchy_name = get_hierarchy_name(obj)
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("administrativelevels", "0004_alter_administrativeunit_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="administrativeunit",
            name="hierarchy_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RunPython(populate_hierarchy_name, migrations.RunPython.noop),
    ]
