# Generated by Django 4.2.20 on 2026-04-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrativelevels", "0005_administrativeunit_hierarchy_name"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="administrativeunit",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="administrativeunit",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent__isnull", False)),
                fields=("name", "parent"),
                name="unique_name_per_parent",
            ),
        ),
        migrations.AddConstraint(
            model_name="administrativeunit",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent__isnull", True)),
                fields=("name",),
                name="unique_root_name",
            ),
        ),
    ]
