# Generated by Django 5.2.17 on 2026-10-07 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativelevels', '0006_unique_name_parent_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativeunit',
            name='zone',
            field=models.CharField(blank=True, choices=[('urban', 'Urbaine'), ('rural', 'Rurale')], default='', max_length=8),
        ),
    ]
