# Generated by Django 4.2.20 on 2025-03-18 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrativelevels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficiaryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('observations', models.TextField(blank=True, null=True)),
                (
                    'conducted_by',
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Subproject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('planned', 'Planned'),
                            ('ongoing', 'Ongoing'),
                            ('completed', 'Completed'),
                            ('paused', 'Paused'),
                            ('canceled', 'Canceled'),
                        ],
                        default='planned',
                        max_length=20,
                    ),
                ),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('latest_construction_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('latest_disbursement_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                (
                    'administrative_levels',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='subprojects',
                        to='administrativelevels.administrativelevel',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='SubprojectBeneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiary_count', models.PositiveIntegerField(default=0)),
                (
                    'beneficiary_group',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='subproject_data',
                        to='subprojects.beneficiarygroup',
                    ),
                ),
                (
                    'subproject',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='beneficiary_data',
                        to='subprojects.subproject',
                    ),
                ),
            ],
            options={
                'unique_together': {('subproject', 'beneficiary_group')},
            },
        ),
        migrations.AddField(
            model_name='subproject',
            name='beneficiary_groups',
            field=models.ManyToManyField(
                through='subprojects.SubprojectBeneficiary', to='subprojects.beneficiarygroup'
            ),
        ),
        migrations.AddField(
            model_name='subproject',
            name='contractors',
            field=models.ManyToManyField(related_name='subprojects', to='subprojects.contractor'),
        ),
        migrations.CreateModel(
            name='SiteVisitImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='site_visits/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                (
                    'site_visit',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='visit_images',
                        to='subprojects.sitevisit',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='subproject',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='site_visits', to='subprojects.subproject'
            ),
        ),
        migrations.CreateModel(
            name='ProgressUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateField(auto_now_add=True)),
                ('construction_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('disbursement_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    'subproject',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='progress_updates',
                        to='subprojects.subproject',
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='subproject_documents/')),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                (
                    'subproject',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='documents',
                        to='subprojects.subproject',
                    ),
                ),
                (
                    'uploaded_by',
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
