# Generated by Django 4.2.20 on 2025-05-02 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("administrativelevels", "0003_alter_administrativelevel_order"),
        ("subprojects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subproject",
            name="administrative_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subprojects",
                to="administrativelevels.administrativeunit",
            ),
        ),
    ]
