# Generated by Django 4.2.20 on 2025-05-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subprojects", "0002_alter_subproject_administrative_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="subproject",
            name="external_id",
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
