# Generated by Django 4.2.20 on 2025-05-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subprojects", "0003_subproject_external_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="progressupdate",
            name="disbursement_rate",
        ),
        migrations.AddField(
            model_name="progressupdate",
            name="disbursed_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="progressupdate",
            name="construction_rate",
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
