# Generated by Django 4.2.20 on 2025-05-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subprojects", "0004_remove_progressupdate_disbursement_rate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="progressupdate",
            name="construction_rate",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="subproject",
            name="latest_disbursement_rate",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
