# Generated by Django 4.2.20 on 2025-05-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subprojects", "0005_alter_progressupdate_construction_rate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubprojectCustomFields",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "config_schema",
                    models.JSONField(
                        default=list, help_text="JSON schema + options for the form"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
