# Generated by Django 4.2.20 on 2025-05-09 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subprojects", "0006_subprojectcustomfields"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SubprojectCustomFields",
            new_name="SubprojectCustomField",
        ),
    ]
