# Generated by Django 4.2.20 on 2025-06-27 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("subprojects", "0007_rename_subprojectcustomfields_subprojectcustomfield"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubprojectFormResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "custom_form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="subprojects.subprojectcustomfield",
                    ),
                ),
                (
                    "filled_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subproject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="subprojects.subproject",
                    ),
                ),
            ],
        ),
    ]
