# Generated by Django 4.2.20 on 2025-06-30 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subprojects", "0008_subprojectformresponse"),
    ]

    operations = [
        migrations.AddField(
            model_name="subproject",
            name="activity_sector",
            field=models.CharField(
                blank=True,
                choices=[
                    ("agropastoralism", "Agropastoralism"),
                    ("local_economy", "Local economy"),
                    ("sports_and_leisure", "Sports and leisure"),
                    ("connectivity", "Connectivity"),
                    ("agropastoralism", "Agropastoralism"),
                    ("water_access", "Water access"),
                    ("education", "Education"),
                    ("public_health", "Public health"),
                    ("hygiene_and_sanitation", "Hygiene and sanitation"),
                    ("public_lighting", "Public lighting"),
                    ("drinking_water_access", "Drinking water access"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="subproject",
            name="community_grant_agreement_reference",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="subproject",
            name="estimate_cost",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="subproject",
            name="objective",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subproject",
            name="project_management",
            field=models.CharField(
                blank=True,
                choices=[("MOC", "MOC"), ("MODC", "MODC")],
                max_length=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="subproject",
            name="sub_component",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1.1", "1.1"),
                    ("1.2a", "1.2a"),
                    ("1.2b", "1.2b"),
                    ("1.3", "1.3"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="subproject",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("infrastructure", "Infrastructure"),
                    ("support_to_gie", "Support to GIE"),
                    (
                        "infrastructure_and_support_to_gie",
                        "Infrastructure & Support to GIE",
                    ),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
