# Generated by Django 4.2.20 on 2025-07-01 13:33

from django.db import migrations, models
import django.db.models.deletion


def remove_subprojectformresponse_subproject_and_more(apps, schema_editor):
    SubprojectFormResponse = apps.get_model('subprojects', 'SubprojectFormResponse')

    sfr_qs = SubprojectFormResponse.objects.all()
    for sfr_q in sfr_qs:
        sfr_q.custom_form.subproject = sfr_q.subproject
        sfr_q.save()


def reverse_remove_subprojectformresponse_subproject_and_more(apps, schema_editor):
    pass


def init_empty_subproject_custom_field(apps, schema_editor):
    SubprojectCustomField = apps.get_model('subprojects', 'SubprojectCustomField')
    Subproject = apps.get_model('subprojects', 'Subproject')
    subproject_obj_default = Subproject.objects.first()
    qs = SubprojectCustomField.objects.filter(subproject=None)
    for obj in qs:
        obj.subproject = subproject_obj_default
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("subprojects", "0009_subproject_activity_sector_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subprojectcustomfield",
            name="subproject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="subprojects.subproject",
            )
        ),
        migrations.RunPython(remove_subprojectformresponse_subproject_and_more, reverse_remove_subprojectformresponse_subproject_and_more),
        migrations.RunPython(init_empty_subproject_custom_field, reverse_remove_subprojectformresponse_subproject_and_more),
        migrations.AlterField(
            model_name="subprojectcustomfield",
            name="subproject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="subprojects.subproject",
            )
        ),
        migrations.RemoveField(
            model_name="subprojectformresponse",
            name="subproject",
        ),
    ]
