# Generated by Django 4.2.20 on 2025-07-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subprojects", "0010_remove_subprojectformresponse_subproject_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subproject",
            name="custom_fields",
        ),
        migrations.AddField(
            model_name="subprojectformresponse",
            name="response_schema",
            field=models.JSONField(default=list, help_text="JSON response schema"),
        ),
        migrations.RemoveField(
            model_name="subprojectcustomfield",
            name="subproject",
        ),
        migrations.AddField(
            model_name="subprojectcustomfield",
            name="subproject",
            field=models.ManyToManyField(
                related_name="custom_fields", to="subprojects.subproject"
            ),
        ),
    ]
