# Generated by Django 4.2.20 on 2025-07-02 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subprojects", "0011_remove_subproject_custom_fields_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subprojectcustomfield",
            old_name="subproject",
            new_name="subprojects",
        ),
    ]
