# Generated by Django 4.2.20 on 2025-07-02 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("subprojects", "0012_rename_subproject_subprojectcustomfield_subprojects"),
    ]

    operations = [
        migrations.AddField(
            model_name="subprojectformresponse",
            name="subproject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="custom_fields_responses",
                to="subprojects.subproject",
            ),
        ),
    ]
