# Generated by Django 4.2.20 on 2025-07-07 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subprojects", "0013_subprojectformresponse_subproject"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subprojectcustomfield",
            name="subprojects",
        ),
    ]
