# Generated by Django 4.2.20 on 2025-07-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subprojects", "0014_remove_subprojectcustomfield_subprojects"),
    ]

    operations = [
        migrations.CreateModel(
            name="DisplayFieldSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(max_length=100, unique=True)),
                ("enabled", models.BooleanField(default=False)),
            ],
        ),
    ]
