# Generated by Django 4.2.20 on 2025-07-09 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("subprojects", "0014_remove_subprojectcustomfield_subprojects"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubprojectCustomFieldDependency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependencies_children",
                        to="subprojects.subprojectcustomfield",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependencies_parents",
                        to="subprojects.subprojectcustomfield",
                    ),
                ),
            ],
        ),
    ]
