# Generated by Django 4.2.20 on 2025-07-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subprojects", "0015_subprojectcustomfielddependency"),
    ]

    operations = [
        migrations.CreateModel(
            name="VillageDevelopmentCommittee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("village_neighborhood", models.CharField(max_length=255)),
                ("name_of_the_sales_representative", models.CharField(max_length=255)),
                (
                    "number_of_male_members_in_the_b_adv_adq_and_its_organs",
                    models.IntegerField(),
                ),
                (
                    "number_of_female_members_in_the_b_adv_adq_and_its_organs",
                    models.IntegerField(),
                ),
                (
                    "number_of_young_members_in_the_b_adv_adq_and_its_organs",
                    models.IntegerField(),
                ),
                ("adv_account_number", models.CharField(max_length=255)),
            ],
        ),
    ]
