# Generated by Django 4.2.20 on 2025-07-09 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subprojects", "0015_displayfieldsetting"),
        ("subprojects", "0016_villagedevelopmentcommittee"),
    ]

    operations = []
