# Generated by Django 4.2.20 on 2025-07-22 12:52

from django.db import migrations, models


def init_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.get_or_create(name='Community facilitator')
    Group.objects.get_or_create(name='Technical facilitator')


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("subprojects", "0017_merge_20250709_2025"),
    ]

    operations = [
        migrations.AddField(
            model_name="subprojectcustomfield",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="subproject_custom_fields",
                to="auth.group",
                verbose_name="Custom Fields",
            ),
        ),
        migrations.RunPython(init_groups),
    ]
