# Generated by Django 4.2.20 on 2025-08-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subprojects", "0019_attachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="file",
            field=models.FileField(
                upload_to="media/subproject_custom_field_attachments/"
            ),
        ),
    ]
