# Generated by Django 4.2.20 on 2025-08-19 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "trackableobjects",
            "0003_remove_followupeventresponse_trackable_object_response",
        ),
        ("subprojects", "0020_alter_attachment_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="follow_up_event_response",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="trackableobjects.followupeventresponse",
            ),
        ),
        migrations.AddField(
            model_name="attachment",
            name="trackable_object_response",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="trackableobjects.trackableobjectresponse",
            ),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="file",
            field=models.FileField(upload_to="media/attachments/"),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="subproject_form_response",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="subprojects.subprojectformresponse",
            ),
        ),
    ]
