# Generated by Django 4.2.20 on 2025-08-28 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subprojects", "0021_attachment_follow_up_event_response_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attachment",
            old_name="trackable_object_response",
            new_name="trackable_object_instance",
        ),
    ]
