# Generated by Django 5.2.17 on 2026-09-30 08:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warning',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_of', models.DateField(help_text='The Monday the warning is issued', unique=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('generated_at', models.DateTimeField()),
                ('paused_count', models.PositiveIntegerField()),
                ('total_field_staff', models.PositiveIntegerField()),
                ('overdue_high_risk_reviews', models.PositiveIntegerField(default=0)),
                ('thresholds', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-week_of'],
            },
        ),
        migrations.CreateModel(
            name='WarningEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('regularity', 'Regularity'), ('quota', 'Quota'), ('rotation', 'Rotation')], max_length=16)),
                ('rank', models.PositiveIntegerField()),
                ('days_since_last_verified', models.IntegerField(blank=True, null=True)),
                ('role', models.CharField(max_length=32)),
                ('threshold_days', models.PositiveIntegerField(blank=True, null=True)),
                ('area', models.CharField(blank=True, max_length=120)),
                ('delta_days', models.IntegerField(blank=True, null=True)),
                ('detail', models.JSONField(default=dict)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('warning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='warning.warning')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
    ]
