# Generated by Django 4.2.20 on 2025-09-09 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=120)),
                ("prefix", models.CharField(default="ACME", max_length=20)),
                (
                    "public_id",
                    models.CharField(db_index=True, max_length=12, unique=True),
                ),
                ("secret_hash", models.CharField(max_length=64)),
                ("scopes", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["public_id"], name="api_apitoke_public__47f2ab_idx"
                    ),
                    models.Index(
                        fields=["user", "revoked_at"],
                        name="api_apitoke_user_id_0370d7_idx",
                    ),
                ],
            },
        ),
    ]
