# Generated by Django 5.2.17 on 2026-09-30 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apitoken',
            name='prefix',
            field=models.CharField(default='MIS', max_length=20),
        ),
    ]
