# Generated by Django 5.2.17 on 2026-09-30 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrativelevels', '0006_unique_name_parent_constraint'),
        ('registry', '0001_initial'),
        ('subprojects', '0023_attachment_sync_fields'),
        ('trackableobjects', '0021_sync_fields'),
        ('visits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='provisionalcoordinate',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='visits.visit'),
        ),
        migrations.AddField(
            model_name='worksite',
            name='commune',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commune_worksites', to='administrativelevels.administrativeunit'),
        ),
        migrations.AddField(
            model_name='worksite',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='worksite',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='region_worksites', to='administrativelevels.administrativeunit'),
        ),
        migrations.AddField(
            model_name='worksite',
            name='subproject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worksites', to='subprojects.subproject'),
        ),
        migrations.AddField(
            model_name='worksite',
            name='trackable_object_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worksites', to='trackableobjects.trackableobjectinstance'),
        ),
        migrations.AddField(
            model_name='worksite',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='worksites', to='administrativelevels.administrativeunit'),
        ),
        migrations.AddField(
            model_name='provisionalcoordinate',
            name='worksite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provisional_coordinates', to='registry.worksite'),
        ),
        migrations.AddField(
            model_name='highriskflagchange',
            name='worksite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='high_risk_changes', to='registry.worksite'),
        ),
        migrations.AddField(
            model_name='worksiteassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='worksiteassignment',
            name='worksite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='registry.worksite'),
        ),
    ]
