# Generated by Django 4.2.20 on 2025-05-21 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("administrativelevels", "0004_alter_administrativeunit_unique_together"),
        (
            "authorization",
            "0002_alter_customuser_options_customuser_date_joined_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="administrative_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="administrativelevels.administrativelevel",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_facilitator",
            field=models.BooleanField(default=False),
        ),
    ]
