# Generated by Django 4.2.20 on 2025-05-21 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("administrativelevels", "0004_alter_administrativeunit_unique_together"),
        ("authorization", "0003_customuser_administrative_level_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="administrative_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="administrativelevels.administrativeunit",
            ),
        ),
    ]
