# Generated by Django 4.2.20 on 2025-05-21 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0004_alter_customuser_administrative_level"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="administrative_level",
            new_name="administrative_unit",
        ),
    ]
