# Generated by Django 4.2.20 on 2025-06-19 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "authorization",
            "0005_rename_administrative_level_customuser_administrative_unit",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="is_facilitator",
            new_name="is_field_agent",
        ),
    ]
