# Generated by Django 4.2.20 on 2026-02-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0006_rename_is_facilitator_customuser_is_field_agent"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
