# Generated by Django 4.2.20 on 2026-03-02 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrativelevels", "0005_administrativeunit_hierarchy_name"),
        ("authorization", "0007_customuser_phone_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="administrative_unit",
        ),
        migrations.AddField(
            model_name="customuser",
            name="administrative_units",
            field=models.ManyToManyField(
                blank=True, to="administrativelevels.administrativeunit"
            ),
        ),
    ]
