# Generated by Django 4.2.20 on 2026-05-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0008_remove_customuser_administrative_unit_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("show_all_activities_button", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Settings",
                "verbose_name_plural": "Settings",
            },
        ),
    ]
