# Generated by Django 5.2.17 on 2026-09-30 08:05

import authorization.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativelevels', '0006_unique_name_parent_constraint'),
        ('authorization', '0009_appsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['full_name', 'email']},
        ),
        migrations.AddField(
            model_name='customuser',
            name='commune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commune_staff', to='administrativelevels.administrativeunit'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='device_class',
            field=models.CharField(choices=[('issued', 'Issued'), ('personal', 'Personal')], default='personal', max_length=16),
        ),
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='customuser',
            name='onboarded_on',
            field=models.DateField(default=authorization.models._today),
        ),
        migrations.AddField(
            model_name='customuser',
            name='preferred_language',
            field=models.CharField(default='fr', max_length=8),
        ),
        migrations.AddField(
            model_name='customuser',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='region_staff', to='administrativelevels.administrativeunit'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('ft', 'Facilitateur technique'), ('fc', 'Facilitateur communautaire'), ('sc', 'Superviseur communal'), ('regional_specialist', 'Spécialiste régional'), ('national_specialist', 'Spécialiste national'), ('rdp', 'Responsable du projet'), ('admin', 'Administrateur')], max_length=32),
        ),
        migrations.AddField(
            model_name='customuser',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='team', to=settings.AUTH_USER_MODEL),
        ),
    ]
