"""
Django settings for src project.

Generated by 'django-admin startproject' using Django 4.2.20.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import environ
import os
from datetime import timedelta
from pathlib import Path

# https://django-environ.readthedocs.io/en/latest/
env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False),
    ALLOWED_HOSTS=(list, ["localhost", "127.0.0.1"]),
    CSRF_TRUSTED_ORIGINS=(list, []),
    CORS_ALLOWED_ORIGINS=(list, []),
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

environ.Env.read_env(os.path.join(BASE_DIR, '.env'))
env.read_env()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# Everything environment-specific comes from the environment (or .env, see .env.example).
# The same code runs the production server and the Vercel demo.
SECRET_KEY = env('SECRET_KEY')
DEBUG = env('DEBUG')
ALLOWED_HOSTS = env('ALLOWED_HOSTS')
CSRF_TRUSTED_ORIGINS = env('CSRF_TRUSTED_ORIGINS')

# GeoDjango needs GDAL/GEOS. On macOS with Homebrew they are usually found
# automatically; set these when they are not.
if env('GDAL_LIBRARY_PATH', default=None):
    GDAL_LIBRARY_PATH = env('GDAL_LIBRARY_PATH')
if env('GEOS_LIBRARY_PATH', default=None):
    GEOS_LIBRARY_PATH = env('GEOS_LIBRARY_PATH')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
    'api.apps.ApiConfig',
    'subprojects',
    'administrativelevels',
    'authorization',
    'trackableobjects',
    # Field monitoring (visits, compliance rules BR-1…BR-15, review, weekly warning).
    'fieldmonitoring.core',
    'fieldmonitoring.registry',
    'fieldmonitoring.visits',
    'fieldmonitoring.review',
    'fieldmonitoring.compliance',
    'fieldmonitoring.warning',
]


THIRD_PARTY_APPS = [
    'bootstrap4',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'drf_yasg',
    'drf_spectacular',
]

INSTALLED_APPS += THIRD_PARTY_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'src.urls'
TEMPLATE_DIR = os.path.join(BASE_DIR, "templates")
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'src.services.overall_variables',
            ],
        },
    },
]

WSGI_APPLICATION = 'src.wsgi.application'


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'api.authentication.BearerApiTokenAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        # The MIS pages call their JSON endpoints from the browser with the session cookie.
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': ['rest_framework.permissions.IsAuthenticated'],
    # drf-spectacular documents the field monitoring API (/api/docs/); the MIS read-only API keeps
    # its drf-yasg pages (/fr/api/v1/swagger/).
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# Long-lived refresh tokens: field staff may be offline for days between syncs (merge plan Q7).
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=env.int('JWT_ACCESS_MINUTES', default=60)),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=env.int('JWT_REFRESH_DAYS', default=30)),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'e3MIS field monitoring API',
    'DESCRIPTION': 'Worksite visit verification API for the field app and the supervision dashboard.',
    'VERSION': '0.2.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'PREPROCESSING_HOOKS': ['fieldmonitoring.core.schema.only_app_api'],
    'ENUM_NAME_OVERRIDES': {'FieldReasonCodeEnum': 'fieldmonitoring.visits.models.FieldReasonCode'},
}

CORS_ALLOWED_ORIGINS = env('CORS_ALLOWED_ORIGINS')

API_KEY_CONFIG = {
    # Changing SECRET_KEY invalidates every issued API token.
    'TOKEN_PEPPER': SECRET_KEY,
    'COMPANY_PREFIX': 'MIS',
}


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Postgres with PostGIS everywhere (field visits need geographic queries). Local default is the
# docker-compose database. A plain postgres:// URL (e.g. Neon) is switched to the PostGIS engine.
DATABASES = {
    'default': env.db('DATABASE_URL', default='postgis://mis:mis@localhost:5434/mis'),
}
DATABASES['default']['ENGINE'] = 'django.contrib.gis.db.backends.postgis'
DATABASES['default']['CONN_MAX_AGE'] = env.int('DB_CONN_MAX_AGE', default=0)


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LOGIN_URL = '/'
LOGOUT_REDIRECT_URL = '/'


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'fr'

LANGUAGES = [
    ('en', 'English'),
    ('fr', 'French'),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',  # or os.path.join(BASE_DIR, 'locale')
]

# Storage and server zone are UTC. Business-day logic uses the programme timezone from
# ProgrammeConfig, never this value.
TIME_ZONE = 'UTC'
PROGRAMME_TIMEZONE_DEFAULT = env('PROGRAMME_TIMEZONE', default='Africa/Abidjan')

# Shared secret for the scheduled-jobs endpoint (/api/v1/jobs/run/). Vercel Cron sends it as a
# Bearer token; on a server, cron can call `manage.py run_jobs` instead.
CRON_SECRET = env('CRON_SECRET', default=None)

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'collected_static'
MEDIA_URL = '/media/'
MEDIA_ROOT = env('MEDIA_ROOT', default=str(BASE_DIR / 'media'))

# Uploaded files (visit photos, form attachments): local disk by default (government server);
# a private Vercel Blob store when its token is set (demo); any S3-compatible bucket when
# AWS_STORAGE_BUCKET_NAME is set. Visit photos are only served through a permission check.
STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage'},
}
if env('BLOB_READ_WRITE_TOKEN', default=None) and not env('AWS_STORAGE_BUCKET_NAME', default=None):
    STORAGES['default'] = {'BACKEND': 'fieldmonitoring.core.storage.VercelBlobStorage'}
if env('AWS_STORAGE_BUCKET_NAME', default=None):
    STORAGES['default'] = {'BACKEND': 'storages.backends.s3.S3Storage'}
    AWS_STORAGE_BUCKET_NAME = env('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_ENDPOINT_URL = env('AWS_S3_ENDPOINT_URL', default=None)
    AWS_DEFAULT_ACL = None
    AWS_QUERYSTRING_AUTH = True

DATA_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024

STATICFILES_DIRS = [
    BASE_DIR / "static",
]
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = '/trackable-objects/mobile'

AUTH_USER_MODEL = 'authorization.CustomUser'

LOGIN_URL = '/'

# Mapbox
MAPBOX_ACCESS_TOKEN = env('MAPBOX_ACCESS_TOKEN', default='')

if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
