# Generated by Django 5.2.17 on 2026-09-30 08:05

import datetime
import django.db.models.deletion
import fieldmonitoring.core.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrativelevels', '0006_unique_name_parent_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=64)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField()),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='JobRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=64)),
                ('run_key', models.CharField(max_length=32)),
                ('ran_at', models.DateTimeField(auto_now_add=True)),
                ('detail', models.JSONField(default=dict)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('job', 'run_key'), name='unique_job_run')],
            },
        ),
        migrations.CreateModel(
            name='ProgrammeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(default='Africa/Abidjan', max_length=64)),
                ('working_days', models.JSONField(default=fieldmonitoring.core.models.default_working_days)),
                ('default_tolerance_m', models.PositiveIntegerField(default=100)),
                ('max_accuracy_m', models.PositiveIntegerField(default=100)),
                ('auto_close_time', models.TimeField(default=datetime.time(20, 0))),
                ('auto_close_grace_minutes', models.PositiveIntegerField(default=60)),
                ('review_sla_hours', models.PositiveIntegerField(default=72)),
                ('rotation_window_days', models.PositiveIntegerField(default=30)),
                ('max_pause_days', models.PositiveIntegerField(default=30)),
                ('impossible_travel_kmh', models.PositiveIntegerField(default=120)),
                ('nearby_radius_m', models.PositiveIntegerField(default=500)),
                ('warning_weekday', models.PositiveSmallIntegerField(default=0)),
                ('warning_time', models.TimeField(default=datetime.time(6, 0))),
                ('photo_reuse_window_days', models.PositiveIntegerField(default=90)),
                ('photo_hash_max_distance', models.PositiveSmallIntegerField(default=6)),
                ('national_at_risk_working_days', models.PositiveSmallIntegerField(default=10)),
                ('capture_token_ttl_minutes', models.PositiveIntegerField(default=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commune_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='administrativelevels.administrativelevel')),
                ('region_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='administrativelevels.administrativelevel')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('village_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='administrativelevels.administrativelevel')),
            ],
            options={
                'verbose_name': 'programme configuration',
            },
        ),
    ]
