# Generated by Django 5.2.17 on 2026-10-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmeconfig',
            name='short_visit_minutes',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
