# Generated by Django 5.2.17 on 2026-10-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_programmeconfig_short_visit_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmeconfig',
            name='max_offline_hours',
            field=models.PositiveIntegerField(default=72),
        ),
    ]
