# Generated by Django 5.2.17 on 2026-10-07 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_programmeconfig_max_offline_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmeconfig',
            name='rural_tolerance_m',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='programmeconfig',
            name='urban_tolerance_m',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
