# Generated by Django 5.2.17 on 2026-09-30 08:05

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('in_progress', 'In progress'), ('verified', 'Verified'), ('unverified', 'Unverified'), ('missed', 'Missed')], max_length=16)),
                ('unverified_reason', models.CharField(blank=True, choices=[('location_failed', 'Location check failed'), ('no_checkout', 'No check-out'), ('mock_location', 'Mock location'), ('no_coordinate', 'Worksite has no coordinate'), ('no_photo', 'Arrival photo not received')], max_length=32, null=True)),
                ('checked_in_at', models.DateTimeField(db_index=True)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('time_on_site_s', models.PositiveIntegerField(blank=True, null=True)),
                ('checkin_location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('checkin_accuracy_m', models.PositiveIntegerField(blank=True, null=True)),
                ('checkin_distance_m', models.PositiveIntegerField(blank=True, null=True)),
                ('checkout_location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('checkout_accuracy_m', models.PositiveIntegerField(blank=True, null=True)),
                ('is_mock_location', models.BooleanField(default=False)),
                ('auto_closed', models.BooleanField(default=False)),
                ('field_reason_code', models.CharField(blank=True, choices=[('battery_died', 'Phone battery died'), ('no_network', 'No network'), ('forgot', 'Forgot to check out'), ('app_closed', 'App closed'), ('no_location_fix', 'Could not get a location fix'), ('other', 'Other')], max_length=32, null=True)),
                ('field_reason', models.TextField(blank=True, null=True)),
                ('field_reason_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True, null=True)),
                ('client_captured_at', models.DateTimeField(blank=True, null=True)),
                ('checkin_idempotency_key', models.CharField(max_length=64)),
                ('checkout_idempotency_key', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'ordering': ['-checked_in_at'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.ImageField(upload_to='photos/%Y/%m/')),
                ('size_bytes', models.PositiveIntegerField()),
                ('perceptual_hash', models.CharField(db_index=True, max_length=16)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('exif_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('exif_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CaptureToken',
            fields=[
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('photo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capture_token', to='visits.photo')),
            ],
        ),
        migrations.CreateModel(
            name='VisitStatus',
            fields=[
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='status', serialize=False, to='visits.visit')),
                ('works_progress', models.CharField(choices=[('on_schedule', 'On schedule'), ('minor_delay', 'Minor delay'), ('stopped', 'Stopped')], max_length=16)),
                ('issue_reported', models.BooleanField()),
                ('note', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='visit',
            name='capture_token',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit', to='visits.capturetoken'),
        ),
        migrations.AddField(
            model_name='visit',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='visits.photo'),
        ),
        migrations.AddField(
            model_name='visit',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visit',
            name='worksite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='registry.worksite'),
        ),
        migrations.CreateModel(
            name='VisitEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.CharField(max_length=32)),
                ('from_state', models.CharField(blank=True, max_length=16, null=True)),
                ('to_state', models.CharField(max_length=16)),
                ('reason', models.CharField(blank=True, max_length=32, null=True)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='visits.visit')),
            ],
            options={
                'ordering': ['at'],
            },
        ),
        migrations.CreateModel(
            name='VisitFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('mock_location', 'Mock location'), ('impossible_travel', 'Impossible travel'), ('photo_reuse', 'Photo reuse'), ('rotation_repeat', 'Rotation repeat')], max_length=32)),
                ('detail', models.JSONField(default=dict)),
                ('raised_at', models.DateTimeField(auto_now_add=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='visits.visit')),
            ],
            options={
                'ordering': ['raised_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='visit',
            constraint=models.UniqueConstraint(fields=('user', 'checkin_idempotency_key'), name='unique_checkin_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='visit',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('state', 'unverified'), ('unverified_reason__isnull', False)), models.Q(models.Q(('state', 'unverified'), _negated=True), ('unverified_reason__isnull', True)), _connector='OR'), name='unverified_reason_matches_state'),
        ),
        migrations.AddConstraint(
            model_name='visit',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('state', 'missed'), _negated=True), ('resolved_by__isnull', False), _connector='OR'), name='missed_requires_resolver'),
        ),
    ]
