# Generated by Django 5.2.17 on 2026-10-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitstatus',
            name='issue_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
