# Generated by Django 5.2.17 on 2026-10-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_visitstatus_issue_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='checkin_received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='checkin_time_source',
            field=models.CharField(choices=[('server', 'Server time at receipt'), ('phone_clock', 'Trusted clock (recorded offline)'), ('unproven', 'Unproven offline time')], default='server', max_length=16),
        ),
        migrations.AddField(
            model_name='visit',
            name='checkout_received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='checkout_time_source',
            field=models.CharField(blank=True, choices=[('server', 'Server time at receipt'), ('phone_clock', 'Trusted clock (recorded offline)'), ('unproven', 'Unproven offline time')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='unverified_reason',
            field=models.CharField(blank=True, choices=[('location_failed', 'Location check failed'), ('no_checkout', 'No check-out'), ('mock_location', 'Mock location'), ('no_coordinate', 'Worksite has no coordinate'), ('no_photo', 'Arrival photo not received'), ('time_unproven', 'Offline time could not be proven')], max_length=32, null=True),
        ),
    ]
