# Generated by Django 5.2.17 on 2026-10-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0003_visit_trusted_clock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='unverified_reason',
            field=models.CharField(blank=True, choices=[('location_failed', 'Location check failed'), ('no_checkout', 'No check-out'), ('mock_location', 'Mock location'), ('no_coordinate', 'Worksite has no coordinate'), ('no_photo', 'Arrival photo not received'), ('time_unproven', 'Offline time could not be proven'), ('form_missing', 'No form saved during the visit')], max_length=32, null=True),
        ),
    ]
