# Generated by Django 4.2.20 on 2025-08-19 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("trackableobjects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="followupevent",
            name="trackable_object",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="follow_up_events",
                to="trackableobjects.trackableobject",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="trackableobjectresponse",
            name="trackable_object",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responses",
                to="trackableobjects.trackableobject",
            ),
        ),
        migrations.CreateModel(
            name="FollowUpEventDependency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependencies_children",
                        to="trackableobjects.followupevent",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependencies_parents",
                        to="trackableobjects.followupevent",
                    ),
                ),
            ],
        ),
    ]
