# Generated by Django 4.2.20 on 2025-08-19 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trackableobjects", "0002_followupevent_trackable_object_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="followupeventresponse",
            name="trackable_object_response",
        ),
    ]
