# Generated by Django 4.2.20 on 2025-08-21 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "trackableobjects",
            "0003_remove_followupeventresponse_trackable_object_response",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="followupeventresponse",
            name="jsonForm",
            field=models.JSONField(default=list, help_text="JSON response schema"),
        ),
        migrations.AlterField(
            model_name="followupeventresponse",
            name="follow_up_event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responses",
                to="trackableobjects.followupevent",
            ),
        ),
    ]
