# Generated by Django 4.2.20 on 2025-08-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("trackableobjects", "0004_followupeventresponse_jsonform_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="followupevent",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="follow_up_events",
                to="auth.group",
                verbose_name="Groups",
            ),
        ),
        migrations.AlterField(
            model_name="trackableobject",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="trackable_objects",
                to="auth.group",
                verbose_name="Groups",
            ),
        ),
    ]
