# Generated by Django 4.2.20 on 2025-08-26 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("trackableobjects", "0005_followupevent_groups_alter_trackableobject_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="followupeventresponse",
            name="trackable_object_response",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trackable_object_responses",
                to="trackableobjects.trackableobjectresponse",
            ),
        ),
    ]
