# Generated by Django 4.2.20 on 2025-08-28 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "subprojects",
            "0022_rename_trackable_object_response_attachment_trackable_object_instance",
        ),
        ("trackableobjects", "0006_followupeventresponse_trackable_object_response"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TrackableObjectResponse",
            new_name="TrackableObjectInstance",
        ),
        migrations.RemoveField(
            model_name="followupeventresponse",
            name="trackable_object_response",
        ),
        migrations.AddField(
            model_name="followupeventresponse",
            name="trackable_object_instance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trackable_object_instances",
                to="trackableobjects.trackableobjectinstance",
            ),
        ),
    ]
