# Generated by Django 4.2.20 on 2025-08-28 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        (
            "trackableobjects",
            "0007_rename_trackableobjectresponse_trackableobjectinstance_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="trackableobjectinstance",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="trackable_object_instances",
                to="auth.group",
                verbose_name="Groups",
            ),
        ),
        migrations.AlterField(
            model_name="trackableobjectinstance",
            name="trackable_object",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="instances",
                to="trackableobjects.trackableobject",
            ),
        ),
    ]
