# Generated by Django 4.2.20 on 2025-08-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrativelevels", "0004_alter_administrativeunit_unique_together"),
        ("trackableobjects", "0008_trackableobjectinstance_groups_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trackableobjectinstance",
            name="administrative_units",
            field=models.ManyToManyField(
                blank=True,
                related_name="trackable_object_instances",
                to="administrativelevels.administrativeunit",
                verbose_name="Administrative units",
            ),
        ),
    ]
