# Generated by Django 4.2.20 on 2025-08-31 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trackableobjects", "0009_trackableobjectinstance_administrative_units"),
    ]

    operations = [
        migrations.AddField(
            model_name="followupevent",
            name="is_one_off",
            field=models.BooleanField(default=False),
        ),
    ]
