# Generated by Django 4.2.20 on 2025-09-01 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("trackableobjects", "0010_followupevent_is_one_off"),
    ]

    operations = [
        migrations.AlterField(
            model_name="followupeventresponse",
            name="trackable_object_instance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="follow_up_responses",
                to="trackableobjects.trackableobjectinstance",
            ),
        ),
    ]
