# Generated by Django 4.2.20 on 2025-09-02 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "trackableobjects",
            "0011_alter_followupeventresponse_trackable_object_instance",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="followupevent",
            name="identifier_field",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="trackableobject",
            name="identifier_field",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
