# Generated by Django 4.2.20 on 2025-09-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trackableobjects", "0012_followupevent_identifier_field_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="followupevent",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
