# Generated by Django 4.2.20 on 2025-10-06 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("trackableobjects", "0013_followupevent_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="followupevent",
            name="trackable_object",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="follow_up_events",
                to="trackableobjects.trackableobject",
            ),
        ),
    ]
