# Generated by Django 4.2.20 on 2025-10-06 13:59

from django.db import migrations, models


def remove_trackable_migration(apps, schema_editor):
    FollowUpEvent = apps.get_model('trackableobjects', 'FollowUpEvent')
    queryset = FollowUpEvent.objects.all()
    for obj in queryset:
        obj.trackable_objects.add(obj.trackable_object)


class Migration(migrations.Migration):

    dependencies = [
        ("trackableobjects", "0014_alter_followupevent_trackable_object"),
    ]

    operations = [
        migrations.AddField(
            model_name="followupevent",
            name="trackable_objects",
            field=models.ManyToManyField(
                blank=True,
                related_name="follow_up_events",
                to="trackableobjects.trackableobject",
            ),
        ),
        migrations.RunPython(remove_trackable_migration),
        migrations.RemoveField(
            model_name="followupevent",
            name="trackable_object",
        ),
    ]
