# Generated by Django 4.2.20 on 2026-04-06 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trackableobjects", "0015_remove_followupevent_trackable_object_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trackableobjectinstance",
            name="restrict_by_administrative_units",
            field=models.BooleanField(
                default=True, verbose_name="Restrict by administrative units"
            ),
        ),
    ]
