# Generated by Django 4.2.20 on 2026-04-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trackableobjects", "0017_followupeventtrackableobject_through_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="trackableobject",
            name="color",
            field=models.CharField(
                choices=[
                    ("amber", "Amber"),
                    ("green", "Green"),
                    ("blue", "Blue"),
                    ("purple", "Purple"),
                    ("coral", "Coral"),
                    ("teal", "Teal"),
                    ("indigo", "Indigo"),
                    ("pink", "Pink"),
                    ("brown", "Brown"),
                    ("slate", "Slate"),
                ],
                default="slate",
                help_text="One of the 10 approved color tokens",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="trackableobject",
            name="icon",
            field=models.CharField(
                default="fa-cube",
                help_text="Font Awesome free (solid) identifier, e.g. 'fa-home'",
                max_length=64,
            ),
        ),
    ]
