# Generated by Django 4.2.20 on 2026-05-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trackableobjects", "0018_icon_color_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="followupevent",
            options={"ordering": ["order", "name"]},
        ),
        migrations.AlterModelOptions(
            name="followupeventtrackableobject",
            options={},
        ),
        migrations.RemoveField(
            model_name="followupeventtrackableobject",
            name="order",
        ),
        migrations.AddField(
            model_name="followupevent",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
