# Generated by Django 5.2.17 on 2026-09-30 05:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativelevels', '0006_unique_name_parent_constraint'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('trackableobjects', '0020_fix_duplicate_followupevent_orders'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='followupevent',
            name='schema_version',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name='followupeventresponse',
            name='client_uuid',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='followupeventresponse',
            name='schema_version',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='followupeventresponse',
            name='version',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name='trackableobject',
            name='schema_version',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name='trackableobjectinstance',
            name='client_uuid',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='trackableobjectinstance',
            name='schema_version',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='trackableobjectinstance',
            name='version',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
        migrations.AddIndex(
            model_name='followupeventresponse',
            index=models.Index(fields=['updated_at'], name='trackableob_updated_119f2e_idx'),
        ),
        migrations.AddIndex(
            model_name='trackableobjectinstance',
            index=models.Index(fields=['updated_at'], name='trackableob_updated_0f107a_idx'),
        ),
    ]
