# Generated by Django 5.2.17 on 2026-10-07 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackableobjects', '0021_sync_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='followupevent',
            name='stage_rules',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='followupevent',
            name='stages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='trackableobject',
            name='creates_worksite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trackableobject',
            name='stages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='trackableobjectinstance',
            name='stage',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.CreateModel(
            name='RecordStageChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_stage', models.CharField(blank=True, max_length=32)),
                ('to_stage', models.CharField(max_length=32)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_changes', to='trackableobjects.trackableobjectinstance')),
                ('response', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='trackableobjects.followupeventresponse')),
            ],
            options={
                'ordering': ['-changed_at', '-id'],
            },
        ),
    ]
