# Generated by Django 5.2.17 on 2026-10-08 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackableobjects', '0022_lifecycle'),
        ('visits', '0004_visit_forms'),
    ]

    operations = [
        migrations.AddField(
            model_name='followupeventresponse',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_responses', to='visits.visit'),
        ),
        migrations.AddField(
            model_name='followupeventresponse',
            name='visit_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='trackableobjectinstance',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_records', to='visits.visit'),
        ),
        migrations.AddField(
            model_name='trackableobjectinstance',
            name='visit_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
